package com.spbweb.entity;

import java.io.Serializable;
import java.util.Date;

public class Storydetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storyDetail.story_id
     *
     * @mbg.generated
     */
    private Integer storyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storyDetail.map_id
     *
     * @mbg.generated
     */
    private Integer mapId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storyDetail.story_title
     *
     * @mbg.generated
     */
    private String storyTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storyDetail.story_description
     *
     * @mbg.generated
     */
    private String storyDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storyDetail.story_setup_date
     *
     * @mbg.generated
     */
    private Date storySetupDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storyDetail.story_last_modified_date
     *
     * @mbg.generated
     */
    private Date storyLastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storyDetail.cood_x
     *
     * @mbg.generated
     */
    private Double coodX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storyDetail.cood_y
     *
     * @mbg.generated
     */
    private Double coodY;

    private String colorPick;

    private String comments;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table storyDetail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storyDetail.story_id
     *
     * @return the value of storyDetail.story_id
     *
     * @mbg.generated
     */
    public Integer getStoryId() {
        return storyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storyDetail.story_id
     *
     * @param storyId the value for storyDetail.story_id
     *
     * @mbg.generated
     */
    public void setStoryId(Integer storyId) {
        this.storyId = storyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storyDetail.map_id
     *
     * @return the value of storyDetail.map_id
     *
     * @mbg.generated
     */
    public Integer getMapId() {
        return mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storyDetail.map_id
     *
     * @param mapId the value for storyDetail.map_id
     *
     * @mbg.generated
     */
    public void setMapId(Integer mapId) {
        this.mapId = mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storyDetail.story_title
     *
     * @return the value of storyDetail.story_title
     *
     * @mbg.generated
     */
    public String getStoryTitle() {
        return storyTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storyDetail.story_title
     *
     * @param storyTitle the value for storyDetail.story_title
     *
     * @mbg.generated
     */
    public void setStoryTitle(String storyTitle) {
        this.storyTitle = storyTitle == null ? null : storyTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storyDetail.story_description
     *
     * @return the value of storyDetail.story_description
     *
     * @mbg.generated
     */
    public String getStoryDescription() {
        return storyDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storyDetail.story_description
     *
     * @param storyDescription the value for storyDetail.story_description
     *
     * @mbg.generated
     */
    public void setStoryDescription(String storyDescription) {
        this.storyDescription = storyDescription == null ? null : storyDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storyDetail.story_setup_date
     *
     * @return the value of storyDetail.story_setup_date
     *
     * @mbg.generated
     */
    public Date getStorySetupDate() {
        return storySetupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storyDetail.story_setup_date
     *
     * @param storySetupDate the value for storyDetail.story_setup_date
     *
     * @mbg.generated
     */
    public void setStorySetupDate(Date storySetupDate) {
        this.storySetupDate = storySetupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storyDetail.story_last_modified_date
     *
     * @return the value of storyDetail.story_last_modified_date
     *
     * @mbg.generated
     */
    public Date getStoryLastModifiedDate() {
        return storyLastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storyDetail.story_last_modified_date
     *
     * @param storyLastModifiedDate the value for storyDetail.story_last_modified_date
     *
     * @mbg.generated
     */
    public void setStoryLastModifiedDate(Date storyLastModifiedDate) {
        this.storyLastModifiedDate = storyLastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storyDetail.cood_x
     *
     * @return the value of storyDetail.cood_x
     *
     * @mbg.generated
     */
    public Double getCoodX() {
        return coodX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storyDetail.cood_x
     *
     * @param coodX the value for storyDetail.cood_x
     *
     * @mbg.generated
     */
    public void setCoodX(Double coodX) {
        this.coodX = coodX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storyDetail.cood_y
     *
     * @return the value of storyDetail.cood_y
     *
     * @mbg.generated
     */
    public Double getCoodY() {
        return coodY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storyDetail.cood_y
     *
     * @param coodY the value for storyDetail.cood_y
     *
     * @mbg.generated
     */
    public void setCoodY(Double coodY) {
        this.coodY = coodY;
    }

    public String getColorPick() {
        return colorPick;
    }

    public void setColorPick(String colorPick) {
        this.colorPick = colorPick;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storyDetail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", storyId=").append(storyId);
        sb.append(", mapId=").append(mapId);
        sb.append(", storyTitle=").append(storyTitle);
        sb.append(", storyDescription=").append(storyDescription);
        sb.append(", storySetupDate=").append(storySetupDate);
        sb.append(", storyLastModifiedDate=").append(storyLastModifiedDate);
        sb.append(", coodX=").append(coodX);
        sb.append(", coodY=").append(coodY);
        sb.append(", colorPick=").append(colorPick);
        sb.append(", comments=").append(comments);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}