package com.spbweb.dao;

import com.spbweb.entity.Logindetail;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;

@Mapper
@Repository
public interface LogindetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginDetail
     *
     * @mbg.generated
     */
    int insert(Logindetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginDetail
     *
     * @mbg.generated
     */
    ArrayList<Logindetail> selectAll();

    int delectUserByName(String name);

    ArrayList<Logindetail> selectByNameAndPasswd(String userName, String userPasswd);


}