package com.spbweb.dao;

import com.spbweb.entity.Logindetail;
import java.util.List;

public interface LogindetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginDetail
     *
     * @mbg.generated
     */
    int insert(Logindetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loginDetail
     *
     * @mbg.generated
     */
    List<Logindetail> selectAll();

}