package com.spbweb.dao;

import com.spbweb.entity.Mapdetail;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.ArrayList;
@Mapper
@Repository
public interface MapdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapDetail
     *
     * @mbg.generated
     */
    int insert(Mapdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapDetail
     *
     * @mbg.generated
     */
    ArrayList<Mapdetail> selectAll();

    Mapdetail findMapByMapId (Integer mapId);

    int deleteMapByMapId (Integer mapId);
}