package com.spbweb.dao;

import com.spbweb.entity.Storydetail;
import java.util.List;

public interface StorydetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storyDetail
     *
     * @mbg.generated
     */
    int insert(Storydetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table storyDetail
     *
     * @mbg.generated
     */
    List<Storydetail> selectAll();
}